### ISSUE TITLE
Revisión de campos de contacto

### ISSUE THREAD

**Issue by cristhiansj** [puyu-pe/qillqay#30]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

*  Los datos de contacto como: ubigeo, dirección y teléfono estan siendo enviados en el objeto company.
* Para los formatos de ticket y a4, estos datos se manejan de manera distinta.

---

## **Describe the solution you'd like**

* Estandarizar la información de contacto para formatos ticket y a4

**Comment by Roel22h** [comment]
TICKET
Modificar el orden de la información de la empresa.

![Image](https://github.com/puyu-pe/qillqay/assets/52603713/e145c238-c445-4019-86da-61057270db41)

El orden planteado para hacer la corrección es:
- Denominación
- Descripción
- Dirección
- Ubigeo
- Teléfono
- RUC

A4
Los siguientes campos no se muestran en este formato.

![Image](https://github.com/puyu-pe/qillqay/assets/52603713/623f639f-0677-4e35-b23b-801f518a10bc)

- Ubigeo
- Telefono
